apiVersion: v1
kind: Service
metadata:
  name: gamebot
  labels:
    name: gamebot    
spec:
  selector:
    name: gamebot    
  type: LoadBalancer
  ports:
   - port: 80
     name: gamebot
     targetPort: 8080
     protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamebot
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gamebot      
  minReadySeconds: 5
  strategy:
    strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: gamebot        
    spec:
      # imagePullSecrets:
      #   - name: teamregistry
      containers:
      - name: gamebot
        image: cyberacrcac168.azurecr.io/gamebot:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            name: gamebot         
            protocol: TCP
        env: 
          - name: "PORT"
            value: "8080"
          - name: "PICK_STRATEGY"
            value: "RANDOM"
          - name: "FF_BETS"
            value: "false"
          - name: "APPINSIGHTS_INSTRUMENTATIONKEY"
            value: "eeabce66-19d4-4d9f-8f13-3cf96e9adc8e"            
